"""
image_sizes.py — record the intrinsic size of every project screenshot.

The case-study page sets width/height on each <img> from this map, so a lazy
image reserves its box and nothing jumps as the page loads.

Run from the repo root:  python3 scripts/image_sizes.py
"""
import os, glob, json
from PIL import Image

ROOT = os.path.join(os.path.dirname(__file__), "..")
OUT = os.path.join(ROOT, "assets", "js", "img-sizes.js")

sizes = {}
for path in sorted(glob.glob(os.path.join(ROOT, "assets", "img", "**", "*.*"), recursive=True)):
    ext = os.path.splitext(path)[1].lower()
    if ext not in (".jpg", ".jpeg", ".png", ".webp"):
        continue
    rel = os.path.relpath(path, ROOT).replace(os.sep, "/")
    if "/crayon/" in rel or "/face/" in rel or "/doodle/" in rel or "/tex/" in rel:
        continue
    sizes[rel] = list(Image.open(path).size)

with open(OUT, "w") as f:
    f.write("/* generated by scripts/image_sizes.py — intrinsic sizes, so lazy images reserve their box */\n")
    f.write("window.IMG_SIZES = " + json.dumps(sizes, sort_keys=True, separators=(",", ":")) + ";\n")
print("wrote", OUT, len(sizes), "images")
